spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database: POSTGRESQL
    hibernate:
      ddl-auto: none
    show-sql: 'true'
    open-in-view: false
  sql:
    init:
      platform: postgres

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:9090/eureka
  instance:
    preferIpAddress: true

logging:
  level:
    root: INFO
    sql: INFO
    web: INFO
